global_cfg:
  run_strategy: mp
  output_dir: ./eff_hists/2_21_25
  json_dir: ./json_files/Eras_CDEFG
  test: False


data_samples:
  # - name: data_L1_11p0_HLT_6p5_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_11p0_HLT_6p5_Excl/CRAB_UserFiles/crab_L1_11p0_HLT_6p5_Excl_02_19_25/250219_211312/0000
  #   trigger: L1_11p0_HLT_6p5_Excl
  #   presel: null

  - name: data_trigger_OR_test
    inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/trigger_OR/CRAB_UserFiles/crab_trigger_OR_02_19_25/250219_211608/0000/output_skim_11*.root
    trigger: trigger_OR
    presel: null

  # - name: data_trigger_OR
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/trigger_OR/CRAB_UserFiles/crab_trigger_OR_02_19_25/250219_211608/0000/
  #   trigger: trigger_OR
  #   presel: null

  # - name: data_L1_10p5_HLT_6p5_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_10p5_HLT_6p5_Excl/CRAB_UserFiles/crab_L1_10p5_HLT_6p5_Excl_02_19_25/250219_211324/0000
  #   trigger: L1_10p5_HLT_6p5_Excl
  #   presel: null

  # - name: data_L1_10p5_HLT_5p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_10p5_HLT_5p0_Excl/CRAB_UserFiles/crab_L1_10p5_HLT_5p0_Excl_02_19_25/250219_211336/0000
  #   trigger: L1_10p5_HLT_5p0_Excl
  #   presel: null

  # - name: data_L1_9p0_HLT_6p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_9p0_HLT_6p0_Excl/CRAB_UserFiles/crab_L1_9p0_HLT_6p0_Excl_02_19_25/250219_211348/0000
  #   trigger: L1_9p0_HLT_6p0_Excl
  #   presel: null

  # - name: data_L1_8p5_HLT_5p5_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_8p5_HLT_5p5_Excl/CRAB_UserFiles/crab_L1_8p5_HLT_5p5_Excl_02_19_25/250219_211410/0000
  #   trigger: L1_8p5_HLT_5p5_Excl
  #   presel: null

  # - name: data_L1_8p5_HLT_5p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_8p5_HLT_5p0_Excl/CRAB_UserFiles/crab_L1_8p5_HLT_5p0_Excl_02_19_25/250219_211358/0000
  #   trigger: L1_8p5_HLT_5p0_Excl
  #   presel: null

  # - name: data_L1_8p0_HLT_5p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_8p0_HLT_5p0_Excl/CRAB_UserFiles/crab_L1_8p0_HLT_5p0_Excl_02_19_25/250219_211421/0000
  #   trigger: L1_8p0_HLT_5p0_Excl
  #   presel: null

  # - name: data_L1_7p5_HLT_5p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_7p5_HLT_5p0_Excl/CRAB_UserFiles/crab_L1_7p5_HLT_5p0_Excl_02_19_25/250219_211433/0000
  #   trigger: L1_7p5_HLT_5p0_Excl
  #   presel: null

  # - name: data_L1_7p0_HLT_5p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_7p0_HLT_5p0_Excl/CRAB_UserFiles/crab_L1_7p0_HLT_5p0_Excl_02_19_25/250219_211446/0000
  #   trigger: L1_7p0_HLT_5p0_Excl
  #   presel: null

  # - name: data_L1_6p5_HLT_4p5_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_6p5_HLT_4p5_Excl/CRAB_UserFiles/crab_L1_6p5_HLT_4p5_Excl_02_19_25/250219_211458/0000
  #   trigger: L1_6p5_HLT_4p5_Excl
  #   presel: null

  # - name: data_L1_6p0_HLT_4p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_6p0_HLT_4p0_Excl/CRAB_UserFiles/crab_L1_6p0_HLT_4p0_Excl_02_19_25/250219_211511/0000
  #   trigger: L1_6p0_HLT_4p0_Excl
  #   presel: null

  # - name: data_L1_5p5_HLT_6p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_5p5_HLT_6p0_Excl/CRAB_UserFiles/crab_L1_5p5_HLT_6p0_Excl_02_19_25/250219_211522/0000
  #   trigger: L1_5p5_HLT_6p0_Excl
  #   presel: null

  # - name: data_L1_5p5_HLT_4p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_5p5_HLT_4p0_Excl/CRAB_UserFiles/crab_L1_5p5_HLT_4p0_Excl_02_19_25/250219_211534/0000
  #   trigger: L1_5p5_HLT_4p0_Excl
  #   presel: null

  # - name: data_L1_5p0_HLT_4p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_5p0_HLT_4p0_Excl/CRAB_UserFiles/crab_L1_5p0_HLT_4p0_Excl_02_19_25/250219_211545/0000
  #   trigger: L1_5p0_HLT_4p0_Excl
  #   presel: null

  # - name: data_L1_4p5_HLT_4p0_Excl
  #   inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/L1_4p5_HLT_4p0_Excl/CRAB_UserFiles/crab_L1_4p5_HLT_4p0_Excl_02_19_25/250219_211556/0000
  #   trigger: L1_4p5_HLT_4p0_Excl
  #   presel: null


mc_samples:
  - name: jpsi_trigger_OR_test
    inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/jpsi_resonant_private
    triggers:
      - trigger_OR
    presel: null

  - name: jpsi_resonant
    inputs: /eos/cms/store/group/phys_bphys/DiElectronX/nzipper/ParkingDoubleMuonLowMassSkims/jpsi_resonant_private
    triggers:
      - trigger_OR
      - L1_11p0_HLT_6p5_Excl
      - L1_10p5_HLT_6p5_Excl
      - L1_10p5_HLT_5p0_Excl
      - L1_9p0_HLT_6p0_Excl
      - L1_8p5_HLT_5p5_Excl
      - L1_8p5_HLT_5p0_Excl
      - L1_8p0_HLT_5p0_Excl
      - L1_7p5_HLT_5p0_Excl
      - L1_7p0_HLT_5p0_Excl
      - L1_6p5_HLT_4p5_Excl
      - L1_6p0_HLT_4p0_Excl
      - L1_5p5_HLT_6p0_Excl
      - L1_5p5_HLT_4p0_Excl
      - L1_5p0_HLT_4p0_Excl
      - L1_4p5_HLT_4p0_Excl
    presel: null


triggers:
  L1_11p0_HLT_6p5_Excl:
    name: L1_11p0_HLT_6p5
    lint: 1.577
    dr_cut: 0.6
    pt_cut: 11.0
    json_file: L1_11p0_HLT_6p5_Excl_Final.json

  L1_10p5_HLT_6p5_Excl:
    name: L1_10p5_HLT_6p5
    lint: 1.135
    dr_cut: 0.6
    pt_cut: 10.5
    json_file: L1_10p5_HLT_6p5_Excl_Final.json

  L1_10p5_HLT_5p0_Excl:
    name: L1_10p5_HLT_5p0
    lint: 0.102
    dr_cut: 0.6
    pt_cut: 10.5
    json_file: L1_10p5_HLT_5p0_Excl_Final.json

  L1_9p0_HLT_6p0_Excl:
    name: L1_9p0_HLT_6p0
    lint: 8.844
    dr_cut: 0.7
    pt_cut: 9.0
    json_file: L1_9p0_HLT_6p0_Excl_Final.json

  L1_8p5_HLT_5p5_Excl:
    name: L1_8p5_HLT_5p5
    lint: 3.339
    dr_cut: 0.7
    pt_cut: 8.5
    json_file: L1_8p5_HLT_5p5_Excl_Final.json

  L1_8p5_HLT_5p0_Excl:
    name: L1_8p5_HLT_5p0
    lint: 0.674
    dr_cut: 0.7
    pt_cut: 8.5
    json_file: L1_8p5_HLT_5p0_Excl_Final.json

  L1_8p0_HLT_5p0_Excl:
    name: L1_8p0_HLT_5p0
    lint: 6.890
    dr_cut: 0.7
    pt_cut: 8.0
    json_file: L1_8p0_HLT_5p0_Excl_Final.json

  L1_7p5_HLT_5p0_Excl:
    name: L1_7p5_HLT_5p0
    lint: 1.635
    dr_cut: 0.7
    pt_cut: 7.5
    json_file: L1_7p5_HLT_5p0_Excl_Final.json

  L1_7p0_HLT_5p0_Excl:
    name: L1_7p0_HLT_5p0
    lint: 2.662
    dr_cut: 0.8
    pt_cut: 7.0
    json_file: L1_7p0_HLT_5p0_Excl_Final.json

  L1_6p5_HLT_4p5_Excl:
    name: L1_6p5_HLT_4p5
    lint: 3.611
    dr_cut: 0.8
    pt_cut: 6.5
    json_file: L1_6p5_HLT_4p5_Excl_Final.json

  L1_6p0_HLT_4p0_Excl:
    name: L1_6p0_HLT_4p0
    lint: 2.511
    dr_cut: 0.8
    pt_cut: 6.0
    json_file: L1_6p0_HLT_4p0_Excl_Final.json

  L1_5p5_HLT_6p0_Excl:
    name: L1_5p5_HLT_6p0
    lint: 0.149
    dr_cut: 0.8
    pt_cut: 5.5
    json_file: L1_5p5_HLT_6p0_Excl_Final.json

  L1_5p5_HLT_4p0_Excl:
    name: L1_5p5_HLT_4p0
    lint: 0.648
    dr_cut: 0.8
    pt_cut: 5.5
    json_file: L1_5p5_HLT_4p0_Excl_Final.json

  L1_5p0_HLT_4p0_Excl:
    name: L1_5p0_HLT_4p0
    lint: 0.041
    dr_cut: 0.9
    pt_cut: 5.0
    json_file: L1_5p0_HLT_4p0_Excl_Final.json

  L1_4p5_HLT_4p0_Excl:
    name: L1_4p5_HLT_4p0
    lint: 0.029
    dr_cut: 0.9
    pt_cut: 4.5
    json_file: L1_4p5_HLT_4p0_Excl_Final.json

  trigger_OR:
    name: trigger_OR
    lint: 33.85
    dr_cut: 0.9
    pt_cut: 4.5
    json_file: trigger_OR.json

